# Generated by Django 6.1.2 on 2026-10-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHYSICIAN', 'Physician'), ('SURGEON', 'Surgeon'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('RADIOLOGIST', 'Radiologist'), ('TECHNICIAN', 'Technician'), ('EXECUTIVE', 'Executive'), ('CLERK', 'Clerk'), ('OFFICE_ASSISTANT', 'Office Assistant')], max_length=20),
        ),
    ]
